# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: PostgreSQL
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: PostgreSQL
    # <string, required> datasource type. Required
    type: postgres
    # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
    access: proxy
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string> url
    url: postgres
    # <string> database user, if used
    user: $POSTGRES_USER
    # <string> database name, if used
    database: smartfactory
    # <bool> enable/disable basic auth
    basicAuth: false
    # <string> basic auth username
    basicAuthUser:
    # <string> Deprecated, use secureJsonData.basicAuthPassword
    basicAuthPassword:
    # <bool> enable/disable with credentials headers
    withCredentials: false
    # <bool> mark as default datasource. Max one per org
    isDefault: false
    # <map> fields that will be converted to json and stored in jsonData
    jsonData:
      postgresVersion: 903
      sslmode: disable
    # <string> json object of data that will be encrypted.
    secureJsonData:
      password: $POSTGRES_PASSWORD
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: false
